# Generated by Django 4.1 on 2022-08-21 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '회사', 'verbose_name_plural': '회사'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '국가', 'verbose_name_plural': '국가'},
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='companies.country', verbose_name='국가'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(max_length=100, verbose_name='지역'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='국가명'),
        ),
    ]
