# Generated by Django 4.1 on 2022-08-21 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_alter_country_options_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '채용공고', 'verbose_name_plural': '채용공고'},
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='companies.company', verbose_name='회사'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='채용내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록일시'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(max_length=100, verbose_name='채용포지션'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reward',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='채용보상금'),
        ),
        migrations.AlterField(
            model_name='post',
            name='skill',
            field=models.CharField(max_length=100, verbose_name='사용기술'),
        ),
    ]
